apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-default-can-deploy-in-dev
  namespace: dev 
subjects:
- kind: ServiceAccount
  name: default     
  namespace: jenkins   
roleRef:
  kind: Role
  name: jenkins-deployment-permissions 
  apiGroup: rbac.authorization.k8s.io