apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      initContainers:
      - name: wait-for-cloud-config
        image: curlimages/curl:7.85.0
        command: ['sh', '-c', 'until curl -f http://cloud-config:9296/actuator/health; do echo waiting for cloud-config; sleep 5; done']
      - name: wait-for-service-discovery
        image: curlimages/curl:7.85.0
        command: ['sh', '-c', 'until curl -f http://service-discovery:8761/actuator/health; do echo waiting for service-discovery; sleep 5; done']
      containers:
      - name: product-service
        image: sebashm1/ecommerce-microservice-backend-app:product
        imagePullPolicy: Always
        ports:
        - containerPort: 8500
        env:
        - name: SPRING_PROFILES_ACTIVE
           value: SPRING_PROFILE_PLACEHOLDER 
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://zipkin:9411/"
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config:9296"
        - name: EUREKA_INSTANCE
          value: "product-service"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8500
          initialDelaySeconds: 25
          periodSeconds: 5
          failureThreshold: 10
