server:
  servlet:
    context-path: /app

spring:
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASE_URL:http://localhost:9411/}
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:9296}
  application:
    name: PROXY-CLIENT
  profiles:
    active:
    - dev

resilience4j:
  retry:
    instances:
      user-service:
        maxAttempts: 3
        waitDuration: 1s
        retryExceptions:
          - java.util.concurrent.TimeoutException
          - feign.FeignException
          - feign.FeignException$InternalServerError
          - feign.FeignException$BadGateway
          - feign.FeignException$ServiceUnavailable
          - feign.FeignException$GatewayTimeout
          - feign.FeignException$Unauthorized
          - feign.FeignException$Forbidden
          - feign.RetryableException
          - java.net.ConnectException
        ignoreExceptions:
          - java.lang.IllegalArgumentException
          - feign.FeignException$NotFound
          - feign.FeignException$BadRequest      order-service:
        maxAttempts: 3
        waitDuration: 1s
        retryExceptions:
          - java.util.concurrent.TimeoutException
          - feign.FeignException
          - feign.FeignException$InternalServerError
          - feign.FeignException$BadGateway
          - feign.FeignException$ServiceUnavailable
          - feign.FeignException$GatewayTimeout
          - feign.FeignException$Unauthorized
          - feign.FeignException$Forbidden
          - feign.RetryableException
          - java.net.ConnectException
        ignoreExceptions:
          - java.lang.IllegalArgumentException
          - feign.FeignException$NotFound
          - feign.FeignException$BadRequest
      product-service:
        maxAttempts: 3
        waitDuration: 1s
        retryExceptions:
          - java.util.concurrent.TimeoutException
          - feign.FeignException
          - feign.FeignException$InternalServerError
          - feign.FeignException$BadGateway
          - feign.FeignException$ServiceUnavailable
          - feign.FeignException$GatewayTimeout
          - feign.FeignException$Unauthorized
          - feign.FeignException$Forbidden
          - feign.RetryableException
          - java.net.ConnectException
        ignoreExceptions:
          - java.lang.IllegalArgumentException
          - feign.FeignException$NotFound
          - feign.FeignException$BadRequest
  timelimiter:
    instances:
      user-service:
        timeoutDuration: 3s
        cancelRunningFuture: true      order-service:
        timeoutDuration: 5s
        cancelRunningFuture: true
      product-service:
        timeoutDuration: 4s
        cancelRunningFuture: true
  circuitbreaker:
    instances:
      proxyService:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        wait-duration-in-open-state: 5s
        sliding-window-type: COUNT_BASED

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

features:
  user-advanced-analytics: true
  smart-recommendations: false
  enhanced-user-profiling: true
  beta-dashboard: false
  premium-insights: true